version: '2'
services:
  backend-template:
    build: ./backend
    container_name: backend-template
    command: npm run start
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
  front-end:
    build: ./frontend
    container_name: front-end
    command: npm run start
    environment:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - "backend-template"
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro