version: '2'
services:
  backend-template:
    build: ./backend
    container_name: backend-template
    command: npm run start
    ports:
      - "3001:3001"
    environment:
      AWS_ACCESS_KEY_ID: AKIAY2N6MOU2HCYDN5H3
      AWS_SECRET_ACCESS_KEY: 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
    depends_on:
      - "mongo"
#  front-end:
#    build: ./frontend
#    container_name: front-end
#    command: npm run start
#    ports:
#      - "3000:3000"
#    depends_on:
#      - "backend-template"
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro