version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-CHANGE_ME} # sample variable
    ports:
      - "3001:3001"