#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "======= running tests before committing ======="

RESPONSE="$(yarn test 2>&1 | grep 'FAIL')"
if [ -z "$RESPONSE" ]
then
	echo "Test all good"
else
	echo "Found FAILING tests:"
	echo $RESPONSE
	exit 1
fi